### ISSUE TITLE
The car can't climb up the slope

### ISSUE THREAD

**Issue by Chortik244** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#10]
The car, instead of going up, crashes and burns. Tell me how to fix it.

**Comment by Rinventor** [comment]
I assume you are driving the on the road (they're not designed for off-road). If the car crashes on driving uphill/downhill then it is because the road is not marked correctly and the car doesn't know it is a road. By that I mean, if the road goes uphill/downhill you have to have it marked using up/down blocks every time the road elevation changes.

**Comment by MagicalAlexey** [comment]
Here is the only negative that crosses out everything

**Comment by MagicalAlexey** [comment]
You can at least allow them to drive on blocks with a small hitbox (according to the type of slab)
