### ISSUE TITLE
Server returning "Internal server error" on join

### ISSUE THREAD

**Issue by DotEXEGaming** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#12]
I have added the files to a server with the newer version of Forge (36.2.34) and have added an already-existing world and server properties. Whenever I try join it returns and "Internal server error" after trying to load the terrain. I have tried deleting player data and checking that all mods are the same, which they are. I am not sure what to do.

**Comment by Rinventor** [comment]
Debug.txt or crash-report.txt would be helpful. I can't test the mod on server at the moment. And I haven't tested it on a server for a long time, so this might not be the only error but if I have some more details I might be able to fix it.

**Comment by Rinventor** [comment]
No need for the logs anymore. I found out what the problem was. I was able to eliminate part of the problem, so that it would not crash. But this means that the player bank account will be empty every time the player joins the server. Should be fixed in version 10 which is probably available in the beginning of August.
