### ISSUE TITLE
entity bug n°2

### ISSUE THREAD

**Issue by Nonoahah506GX** [Rinventor/Public-Transport-Mod-for-Minecraft-Java-edition#5]
excuse me (again) but it seems to me that the 8.0 update of the public transport mod does not fix the entity bug said in the previous message, would there be a way to fix it in game? I await your response...

**Comment by Rinventor** [comment]
Have tried this command: /gamerule clearVehiclesOnWorldLoad false? It might help. 

This problem is deeply buried under various layers of code. But I'm curious which entities exactly dissappear? Cars, transport and pedestrians? But spawners will respawn them after few seconds. Or do they have to be in already there when you join the world?

I'm currently working on next big updates, which will be released at the end of this month. I can fix the issue, when I have little bit more details.

**Comment by Nonoahah506GX** [comment]
so, I'll start with the mobs: there are certain mobs that don't disappear, it's a bit complicated but I think I can give you a little recap on those that disappear, which do you prefer? a list or a video? (a video will be easier for me)...

**Comment by Nonoahah506GX** [comment]
I will try the command but I do not guarantee anything ...

**Comment by Nonoahah506GX** [comment]
the command does not work, sorry

**Comment by Rinventor** [comment]
I found out where exactly the issue was in the code. However, fixing it messes up a lot of other systems since they are all connected in various ways. Since I'm starting to change all the code more efficient and change texturing the transport vehicles screens a lot easier and more compact, it takes time to fix this error. 

I can't guarantee when I can release an early version where this problem will be fixed.

**Comment by Nonoahah506GX** [comment]
ok, I'm waiting for the version in question to test it...

**Comment by Nonoahah506GX** [comment]
hello, it's been a long time since your mod has been updated.
is everything ok on your side?

**Comment by Rinventor** [comment]
Hi! This issue is almost fixed. I working on so many fixes, changes and new features at the moment. I can't update the mod before I have fixed everything. It has really been a long wait, but I hope to get version 9.0 ready by the 23rd of June. Hopefully. :)

**Comment by Nonoahah506GX** [comment]
perfect, I'm impatiently waiting for the next version of the mode, thank you for working so much on this mod which (I've already said it) unique, thank you very much 👌😁

**Comment by Nonoahah506GX** [comment]
I don't have the opportunity to test the mod, but everything seems to work well, I hope I will have a good surprise😁
